apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicio-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
      - name: monitor
        image: servicio-monitor
        ports:
        - containerPort: 80
